//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWS.VnAccounting.Presentation.WebApp.Mods._Demo {
    
    
    public partial class DemoGridBase {
        
        /// <summary>
        /// GridBase1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FWS.VnAccounting.Presentation.WebApp.Mods._Core.GridBase GridBase1;
        
        /// <summary>
        /// GridBase2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FWS.VnAccounting.Presentation.WebApp.Mods._Core.GridBase GridBase2;
    }
}
