//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWS.VnAccounting.Presentation.WebApp.Mods.Inventory {
    
    
    public partial class OutwardStock {
        
        /// <summary>
        /// ucOutStock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::FWS.VnAccounting.Presentation.WebApp.Mods.Inventory.CoreStock ucOutStock;
    }
}
