using System;
using System.Collections.Generic;
using System.Web;

namespace FWS.VnAccounting.Service.Data.WebServiceReference.Soap
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.6407
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CallcenterServiceSoap", Namespace = "http://tempuri.org/")]
    public class CCallcenter : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        public CCallcenter()
        {
            string urlSetting = System.Configuration.ConfigurationManager.AppSettings["Callcenter"];
            if ((urlSetting != null)) {
                this.Url = urlSetting;
            }
            else {
                this.Url = "http://localhost:15825/CallcenterService.asmx";
            }
        }
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendMail", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendMail(string strAddrTo, string strAddCC, string strAddBCC, string strSubject, string strBody, string strFileName1, [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")] byte[] bFileContent1, string strFileName2, [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")] byte[] bFileContent2, string strFileName3, [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")] byte[] bFileContent3)
        {
            object[] results = this.Invoke("SendMail", new object[] {
                    strAddrTo,
                    strAddCC,
                    strAddBCC,
                    strSubject,
                    strBody,
                    strFileName1,
                    bFileContent1,
                    strFileName2,
                    bFileContent2,
                    strFileName3,
                    bFileContent3});
            return ((string)(results[0]));
        }
    }
}